SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE `users` MODIFY               `id` BIGINT      NOT NULL AUTO_INCREMENT,
ADD CONSTRAINT emails_unique UNIQUE (email);
ALTER TABLE `user_roles` MODIFY           `id` BIGINT      NOT NULL AUTO_INCREMENT;
ALTER TABLE `interviews` MODIFY `id` BIGINT      NOT NULL AUTO_INCREMENT;
ALTER TABLE `scheduled_timeslots` MODIFY  `id` BIGINT      NOT NULL AUTO_INCREMENT;
ALTER TABLE `user_skills` MODIFY          `id` BIGINT      NOT NULL AUTO_INCREMENT;
SET FOREIGN_KEY_CHECKS=1;
